name: flutter_apply_villained
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Modestas Valauskas <valauskasmodestas@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_apply:
    git:
      url: git@github.com:modulovalue/flutter_apply.git
      ref: 9459a71a47d4b1a5d1e7f11b889cc9a248833a66
  flutter_hooks: ^0.6.1
  abstract_dart: 0.0.3
  intersperse: 1.0.0

dev_dependencies:
  extra_pedantic: ^1.1.1+2
  test: any
  mockito: ^4.0.0